name: Backend Build

on:
  push:
    branches: [ "main", "dev", "feat/**", "refactor/**", "style/**", "fix/**" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read
  packages: write

jobs:
  detect-services:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.set-matrix.outputs.matrix}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Services List
        id: set-matrix
        run: |
          services=$(ls -d be/services/*/ | xargs -n 1 basename | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$services" >> $GITHUB_OUTPUT

  nx-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Check disk
        run: df -h

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission
        run: chmod +x gradlew
        working-directory: ./apps

      - run: npm install

      - run: npm ci

      - name: Force clean Gradle builds
        run: |
          rm -rf apps/*/build || true

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: apps/.gradle/caches
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}"
          restore-keys: "${{ runner.os }}-gradle"
